In [1]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (1.83.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\dharmesh sharma\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [2]:
import numpy as np

In [3]:
import tensorflow as tf

print(tf.__version__)

2.21.0

In [4]:
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [5]:
df = pd.DataFrame({
    "soil_moisture": [
        0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
        0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30
    ],

    "temperature_c": [
        34, 30, 26, 22, 28, 30, 19, 22,
        35, 24, 33, 33, 21, 25, 20, 29
    ],

    "sunlight_hours": [
        9, 8, 7, 4, 8, 10, 3, 10,
        12, 5, 9, 11, 2, 6, 1, 9
    ],

    "needs_water": [
        1, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1
    ]
})

df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [6]:
X = df.drop("needs_water" , axis =1)

In [7]:
y = df["needs_water"]

In [8]:
X

    soil_moisture  temperature_c  sunlight_hours
0            0.10             34               9
1            0.15             30               8
2            0.20             26               7
3            0.25             22               4
4            0.40             28               8
5            0.60             30              10
6            0.35             19               3
7            0.18             22              10
8            0.45             35              12
9            0.05             24               5
10           0.80             33               9
11           0.27             33              11
12           0.55             21               2
13           0.70             25               6
14           0.12             20               1
15           0.30             29               9

In [9]:
y

0     1
1     1
2     1
3     0
4     0
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    0
14    1
15    1
Name: needs_water, dtype: int64

In [10]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/ (X_max - X_min + 1e-8)

In [11]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [13]:
X_train , X_test , y_train , y_test = train_test_split(X_scaled , y , test_size = 0.25 , random_state = 42)

In [14]:
X_train.shape

(12, 3)

In [15]:
X_train.shape[1]

3

In [16]:
X_train , X_test , y_train , y_test = train_test_split(X_scaled , y , test_size = 0.20 , random_state = 42)

In [18]:
model = keras.Sequential(
    [
        layers.Input(shape = (X_train.shape[1],)),
        layers.Dense(8,activation = "relu"),
        layers.Dense(1 , activation = "sigmoid")
    ]
)

In [21]:
model.compile(optimizer = "sgd" , loss = "binary_crossentropy" , metrics = ["accuracy"])

In [20]:
print("GPUs:", tf.config.list_physical_devices("GPU"))
print("CPUs:", tf.config.list_physical_devices("CPU"))

GPUs: []
CPUs: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [26]:
history = model.fit(
    X_train.values , y_train.values,
    validation_data = (X_test.values  , y_test.values),
    epochs = 100 ,
    batch_size = 4,
    verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.7500 - loss: 0.5612 - val_accuracy: 0.7500 - val_loss: 0.6858
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.5612 - val_accuracy: 0.7500 - val_loss: 0.6852
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.5597 - val_accuracy: 0.7500 - val_loss: 0.6848
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.5598 - val_accuracy: 0.7500 - val_loss: 0.6842
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.5576 - val_accuracy: 0.7500 - val_loss: 0.6837
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7500 - loss: 0.5582 - val_accuracy: 0.7500 - val_loss: 0.6832
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.5570 - val_accuracy: 0.7500 - val_loss: 0.6827
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.5566 - val_accuracy: 0.7500 - val_loss: 0.6822
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.5548 - val_accuracy: 0.7500 - val_loss: 0.6816
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.5554 - val_accuracy: 0.7500 - val_loss: 0.6810
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.5547 - val_accuracy: 0.7500 - val_loss: 0.6804
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 0.5534 - val_accuracy: 0.7500 - val_loss: 0.6798
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 0.5528 - val_accuracy: 0.7500 - val_loss: 0.6793
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5531 - val_accuracy: 0.7500 - val_loss: 0.6788
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5513 - val_accuracy: 0.7500 - val_loss: 0.6782
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5512 - val_accuracy: 0.7500 - val_loss: 0.6777
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5493 - val_accuracy: 0.7500 - val_loss: 0.6771
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5488 - val_accuracy: 0.7500 - val_loss: 0.6764
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5494 - val_accuracy: 0.7500 - val_loss: 0.6757
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5469 - val_accuracy: 0.7500 - val_loss: 0.6751
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5468 - val_accuracy: 0.7500 - val_loss: 0.6746
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5456 - val_accuracy: 0.7500 - val_loss: 0.6740
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5472 - val_accuracy: 0.7500 - val_loss: 0.6735
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 0.5442 - val_accuracy: 0.7500 - val_loss: 0.6728
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.5437 - val_accuracy: 0.7500 - val_loss: 0.6722
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5432 - val_accuracy: 0.7500 - val_loss: 0.6715
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5433 - val_accuracy: 0.7500 - val_loss: 0.6710
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5417 - val_accuracy: 0.7500 - val_loss: 0.6703
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5407 - val_accuracy: 0.7500 - val_loss: 0.6696
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5406 - val_accuracy: 0.7500 - val_loss: 0.6691
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5416 - val_accuracy: 0.7500 - val_loss: 0.6684
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 0.5393 - val_accuracy: 0.7500 - val_loss: 0.6678
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5385 - val_accuracy: 0.7500 - val_loss: 0.6672
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5378 - val_accuracy: 0.7500 - val_loss: 0.6666
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5382 - val_accuracy: 0.7500 - val_loss: 0.6658
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5394 - val_accuracy: 0.7500 - val_loss: 0.6651
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8333 - loss: 0.5363 - val_accuracy: 0.7500 - val_loss: 0.6643
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5343 - val_accuracy: 0.7500 - val_loss: 0.6636
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5354 - val_accuracy: 0.7500 - val_loss: 0.6628
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5329 - val_accuracy: 0.7500 - val_loss: 0.6621
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5320 - val_accuracy: 0.7500 - val_loss: 0.6615
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5331 - val_accuracy: 0.7500 - val_loss: 0.6607
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5312 - val_accuracy: 0.7500 - val_loss: 0.6601
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5312 - val_accuracy: 0.7500 - val_loss: 0.6593
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5293 - val_accuracy: 0.7500 - val_loss: 0.6587
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5288 - val_accuracy: 0.7500 - val_loss: 0.6581
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5284 - val_accuracy: 0.7500 - val_loss: 0.6575
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8333 - loss: 0.5286 - val_accuracy: 0.7500 - val_loss: 0.6567
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5284 - val_accuracy: 0.7500 - val_loss: 0.6560
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5255 - val_accuracy: 0.7500 - val_loss: 0.6553
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5255 - val_accuracy: 0.7500 - val_loss: 0.6546
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5253 - val_accuracy: 0.7500 - val_loss: 0.6538
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8333 - loss: 0.5236 - val_accuracy: 0.7500 - val_loss: 0.6532
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5254 - val_accuracy: 0.7500 - val_loss: 0.6525
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5225 - val_accuracy: 0.7500 - val_loss: 0.6519
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5223 - val_accuracy: 0.7500 - val_loss: 0.6513
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5233 - val_accuracy: 0.7500 - val_loss: 0.6506
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5199 - val_accuracy: 0.7500 - val_loss: 0.6500
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5194 - val_accuracy: 0.7500 - val_loss: 0.6492
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5221 - val_accuracy: 0.7500 - val_loss: 0.6485
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.5190 - val_accuracy: 0.7500 - val_loss: 0.6477
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5170 - val_accuracy: 0.7500 - val_loss: 0.6470
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5160 - val_accuracy: 0.7500 - val_loss: 0.6463
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5182 - val_accuracy: 0.7500 - val_loss: 0.6455
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5162 - val_accuracy: 0.7500 - val_loss: 0.6448
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5143 - val_accuracy: 0.7500 - val_loss: 0.6441
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5139 - val_accuracy: 0.7500 - val_loss: 0.6433
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5127 - val_accuracy: 0.7500 - val_loss: 0.6427
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 0.5130 - val_accuracy: 0.7500 - val_loss: 0.6419
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5109 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5109 - val_accuracy: 0.7500 - val_loss: 0.6406
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5117 - val_accuracy: 0.7500 - val_loss: 0.6398
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5090 - val_accuracy: 0.7500 - val_loss: 0.6392
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 0.5088 - val_accuracy: 0.7500 - val_loss: 0.6385
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5089 - val_accuracy: 0.7500 - val_loss: 0.6379
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5077 - val_accuracy: 0.7500 - val_loss: 0.6373
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5060 - val_accuracy: 0.7500 - val_loss: 0.6366
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5050 - val_accuracy: 0.7500 - val_loss: 0.6359
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5057 - val_accuracy: 0.7500 - val_loss: 0.6351
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5039 - val_accuracy: 0.7500 - val_loss: 0.6345
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.5031 - val_accuracy: 0.7500 - val_loss: 0.6337
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5026 - val_accuracy: 0.7500 - val_loss: 0.6330
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5027 - val_accuracy: 0.7500 - val_loss: 0.6323
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5034 - val_accuracy: 0.7500 - val_loss: 0.6316
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5003 - val_accuracy: 0.7500 - val_loss: 0.6308
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4994 - val_accuracy: 0.7500 - val_loss: 0.6300
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.4988 - val_accuracy: 0.7500 - val_loss: 0.6293
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.4982 - val_accuracy: 0.7500 - val_loss: 0.6287
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.4975 - val_accuracy: 0.7500 - val_loss: 0.6279
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4967 - val_accuracy: 0.7500 - val_loss: 0.6273
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.4958 - val_accuracy: 0.7500 - val_loss: 0.6265
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.4952 - val_accuracy: 0.7500 - val_loss: 0.6258
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.4943 - val_accuracy: 0.7500 - val_loss: 0.6251
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.4937 - val_accuracy: 0.7500 - val_loss: 0.6245
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.9167 - loss: 0.4929 - val_accuracy: 0.7500 - val_loss: 0.6238
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4922 - val_accuracy: 0.7500 - val_loss: 0.6232
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4920 - val_accuracy: 0.7500 - val_loss: 0.6226
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.4915 - val_accuracy: 0.7500 - val_loss: 0.6223
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4921 - val_accuracy: 0.7500 - val_loss: 0.6217
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4902 - val_accuracy: 0.7500 - val_loss: 0.6209